AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy AWS config aggregator with Organization Aggregation Source'
# Metadata:
#   'AWS::CloudFormation::Interface':
#     ParameterGroups:
#     - Label:
#         default: 'Stack Inputs'
#       Parameters:
#       - ProjectName
# #Input Parameters
# Parameters:
#   #Project Name
#   ProjectName:
#     Default: script
#     NoEcho: false
#     Description: Name of the Project to be used in Tags (1-8 char long)
#     Type: String
#     MinLength: 1
#     MaxLength: 8
#     AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"

#Build AWS resources
Resources:
  #IAM role to allow AWS Config to get the list of your accounts in your organization
  AWSConfigAggregateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        !Join
        - '-'
        - - !Ref AWS::StackName
          - 'configuration-aggregator-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - organizations.amazonaws.com
      Path: /
      Policies:
        - PolicyName:
            !Join
            - '-'
            - - !Ref AWS::StackName
              - 'configuration-aggregator-policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "iam:DeleteRole"
                Resource: "arn:aws:iam::*:role/aws-service-role/organizations.amazonaws.com/*"
              - Effect: Allow
                Action: "iam:CreateServiceLinkedRole"
                Resource: "*"  
  #AWS config Aggregator
  ConfigurationAggregator:
    Type: 'AWS::Config::ConfigurationAggregator'
    Properties:
      OrganizationAggregationSource:
        RoleArn: !GetAtt AWSConfigAggregateRole.Arn 
        AllAwsRegions: true
      ConfigurationAggregatorName:
        !Join
        - '-'
        - - !Ref AWS::StackName
          - 'configuration-aggregator'

# Output
Outputs:
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'